baseURL = "https://www.saralarin.ca/"
DefaultContentLanguage = "fr"
title = "Sara Larin | Rédaction Agile"
theme = "saralarin"
description = ""

# Pointing to this file
config = "config.toml"
contentdir = "content"
disableKinds = ["RSS"]
# Create an array of files you don't want hugo to build
ignoreFiles = []
# Enable Logging
log = false
preserveTaxonomyNames = true
pygmentsUseClasses = true
relativeURLs = true
languageCode = "en-us"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = false
EnableMissingTranslationPlaceholders = true

#CUSTOM PARAMS
[params]
  ## Include google maps, with API Key
  googleapikey = ""
  ## This is used when the BaseURL does not need to modified (eg, in share links)
  siteaddress = "https://www.saralarin.ca/"
  siteaddressno = "https://www.saralarin.ca"
  ## FB share info
  fbpagename = ""
  fbappid = ""
  ## Business name in Schema.org
  schemabiz = "Sara Larin"
  ## Google Tag Manager tracking ID
  gtmid = "GTM-NPX35ZC"

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[Languages]
[Languages.en]
[Languages.en.taxonomies]
  category = "categories"
  tag = "tags"
[Languages.en.permalinks]
  singles = "/:slug/"
  category = "categories"

[Languages.fr]
[Languages.fr.taxonomies]
  category = "categories"
  tag = "tags"
[Languages.fr.permalinks]
  singles = "/:slug/"
  category = "categories"

